import streamlit as st

from services.llm_service import (
    generate_scene_plan,
)

from services.image_service import (
    generate_scene_image,
)

from services.tts_service import (
    generate_voice,
)

from services.subtitle_service import (
    create_srt,
)

from services.video_service import (
    build_video,
)

from utils.file_utils import (
    make_job_dir,
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI Educational Video Generator",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    .main-title {
        font-size: 42px;
        font-weight: 800;
        margin-bottom: 5px;
    }

    .subtitle {
        font-size: 18px;
        opacity: 0.75;
        margin-bottom: 25px;
    }

    .section-title {
        font-size: 24px;
        font-weight: 700;
        margin-top: 20px;
        margin-bottom: 10px;
    }

    .info-card {
        padding: 18px;
        border-radius: 14px;
        border: 1px solid rgba(128,128,128,0.25);
        margin-bottom: 12px;
    }

    .scene-card {
        padding: 15px;
        border-radius: 12px;
        border: 1px solid rgba(128,128,128,0.20);
        margin-bottom: 10px;
    }

    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">🎓 AI Educational Video Generator</div>',
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="subtitle">
    Transform educational content into a professional animated
    educational video with AI narration, visuals, subtitles,
    animation and MP4 rendering.
    </div>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("⚙️ Video Settings")

    language = st.selectbox(
        "🌐 Language",
        [
            "English",
            "Hindi",
            "Bengali",
        ],
        index=0,
    )

    education_level = st.selectbox(
        "🎓 Education Level",
        [
            "Class 5",
            "Class 8",
            "Class 10",
            "Class 12",
            "College",
            "General",
        ],
        index=0,
    )

    duration = st.slider(
        "⏱️ Target Video Duration",
        min_value=60,
        max_value=180,
        value=120,
        step=10,
        help="The final duration will depend on the actual narration generated by the AI.",
    )

    visual_mode = st.selectbox(
        "🎨 Visual Mode",
        [
            "Smart Automatic",
            "AI Images",
            "Animation Only",
        ],
        index=0,
    )

    st.divider()

    st.markdown(
        """
        **Current AI Pipeline**

        🧠 Groq + Qwen  
        🎨 Hugging Face + FLUX  
        🗣️ Edge TTS  
        📝 SRT subtitles  
        🎬 FFmpeg  

        **No automatic paid fallback.**
        """
    )


# ============================================================
# MAIN INPUT
# ============================================================

st.markdown(
    '<div class="section-title">📚 Educational Content</div>',
    unsafe_allow_html=True,
)

educational_text = st.text_area(
    "Paste your educational material below",

    height=330,

    placeholder="""
Example:

Meet AIVA, a friendly educational robot.

Today AIVA wants to teach us how Artificial
Intelligence works.

AI allows computers to perform tasks that
normally require human intelligence.

AI can recognize pictures, understand speech,
translate languages and learn patterns from data.

Paste your complete educational material here.
""",

    help=(
        "The AI will convert this material into "
        "scenes, narration and visual instructions."
    ),
)


# ============================================================
# CHARACTER PREVIEW
# ============================================================

with st.expander(
    "🤖 About AIVA",
    expanded=False,
):

    st.markdown(
        """
        **AIVA** is the recurring educational character.

        - 🤖 Friendly educational robot
        - ⚪ White rounded body
        - 🔵 Blue accents
        - 👀 Large expressive blue eyes
        - 💡 Blue glowing chest light
        - 🎒 Small blue educational backpack
        - 😊 Child-friendly personality

        The image-generation system receives the same character
        description for every scene to improve visual consistency.
        """
    )


# ============================================================
# GENERATE BUTTON
# ============================================================

generate_button = st.button(
    "🚀 Generate Educational Video",
    type="primary",
    use_container_width=True,
)


# ============================================================
# GENERATION PIPELINE
# ============================================================

if generate_button:

    # --------------------------------------------------------
    # INPUT VALIDATION
    # --------------------------------------------------------

    clean_text = educational_text.strip()

    if len(clean_text) < 80:

        st.error(
            "❌ Please enter at least 80 characters "
            "of educational content."
        )

        st.stop()

    # --------------------------------------------------------
    # CREATE JOB DIRECTORY
    # --------------------------------------------------------

    job_dir = make_job_dir()

    image_files = []
    audio_files = []
    animations = []

    # IMPORTANT:
    # These are actual TTS durations.
    actual_durations = []

    # --------------------------------------------------------
    # PROGRESS UI
    # --------------------------------------------------------

    progress = st.progress(
        0
    )

    status = st.empty()

    scene_status = st.empty()

    try:

        # ====================================================
        # STEP 1
        # QWEN SCENE PLANNING
        # ====================================================

        status.info(
            "🧠 Step 1/6 — Qwen is analyzing the educational content..."
        )

        plan = generate_scene_plan(
            educational_text=clean_text,
            language=language,
            education_level=education_level,
            target_seconds=duration,
        )

        progress.progress(
            12
        )

        scenes = plan.get(
            "scenes",
            [],
        )

        if not scenes:

            raise RuntimeError(
                "The AI did not create any scenes."
            )

        # ----------------------------------------------------
        # SHOW GENERATED PLAN
        # ----------------------------------------------------

        with st.expander(
            "🧠 View Generated Scene Plan",
            expanded=False,
        ):

            st.json(
                plan
            )

        # ====================================================
        # SCENE GENERATION
        # ====================================================

        total_scenes = len(
            scenes
        )

        for index, scene in enumerate(
            scenes,
            start=1,
        ):

            # =================================================
            # SCENE HEADER
            # =================================================

            scene_status.info(
                f"🎬 Processing scene {index}/{total_scenes}"
            )

            # =================================================
            # STEP 2
            # AI IMAGE
            # =================================================

            status.info(
                f"🎨 Step 2/6 — Creating professional visual "
                f"for scene {index}/{total_scenes}..."
            )

            image_path = (
                job_dir
                / f"scene_{index:02d}.png"
            )

            # -----------------------------------------------
            # IMAGE PROMPT
            # -----------------------------------------------

            image_prompt = scene.get(
                "image_prompt",
                "",
            ).strip()

            if not image_prompt:

                image_prompt = (
                    scene.get(
                        "narration",
                        "",
                    )
                )

            # -----------------------------------------------
            # ANIMATION ONLY MODE
            # -----------------------------------------------

            if visual_mode == "Animation Only":

                image_prompt = """
                Create a clean professional educational
                background suitable for an animated lesson.

                Use a modern classroom and educational
                technology environment.

                Include AIVA when appropriate.

                Premium 3D educational animation style.
                """

            # -----------------------------------------------
            # GENERATE IMAGE
            # -----------------------------------------------

            (
                image_path,
                ai_image_used,
            ) = generate_scene_image(
                prompt=image_prompt,

                on_screen_text=scene.get(
                    "on_screen_text",
                    "",
                ),

                scene_title=plan.get(
                    "title",
                    "Educational Lesson",
                ),

                scene_number=index,

                output_path=image_path,
            )

            image_files.append(
                image_path
            )

            # =================================================
            # STEP 3
            # TEXT TO SPEECH
            # =================================================

            status.info(
                f"🗣️ Step 3/6 — Generating complete AI narration "
                f"for scene {index}/{total_scenes}..."
            )

            audio_path = (
                job_dir
                / f"scene_{index:02d}.mp3"
            )

            narration = scene.get(
                "narration",
                "",
            ).strip()

            if not narration:

                raise RuntimeError(
                    f"Scene {index} has no narration."
                )

            # -----------------------------------------------
            # IMPORTANT:
            # generate_voice now returns:
            #
            # audio_path
            # actual_audio_duration
            #
            # The actual TTS duration controls the video.
            # -----------------------------------------------

            (
                audio_path,
                actual_audio_duration,
            ) = generate_voice(
                text=narration,

                language=language,

                output_path=audio_path,
            )

            audio_files.append(
                audio_path
            )

            actual_durations.append(
                actual_audio_duration
            )

            # =================================================
            # ANIMATION
            # =================================================

            animation = scene.get(
                "animation",
                "camera_push",
            )

            animations.append(
                animation
            )

            # =================================================
            # PROGRESS
            # =================================================

            scene_progress = (
                index
                / total_scenes
            )

            progress_value = (
                15
                + int(
                    45
                    * scene_progress
                )
            )

            progress.progress(
                progress_value
            )

            # -------------------------------------------------
            # SHOW SCENE INFORMATION
            # -------------------------------------------------

            with st.expander(
                f"Scene {index}: "
                f"{scene.get('on_screen_text', 'Educational Scene')}",
                expanded=False,
            ):

                st.write(
                    "**Narration:**"
                )

                st.write(
                    narration
                )

                st.write(
                    "**Animation:** "
                    + str(
                        animation
                    )
                )

                st.write(
                    "**Actual voice duration:** "
                    + f"{actual_audio_duration:.2f} seconds"
                )

                if ai_image_used:

                    st.success(
                        "🎨 AI-generated visual created."
                    )

                else:

                    st.info(
                        "ℹ️ Fallback educational visual used."
                    )

                st.image(
                    str(image_path),
                    use_container_width=True,
                )

        # ====================================================
        # STEP 4
        # SUBTITLES
        # ====================================================

        status.info(
            "📝 Step 4/6 — Synchronizing subtitles "
            "with the actual AI narration..."
        )

        subtitle_path = (
            job_dir
            / "subtitles.srt"
        )

        create_srt(
            scenes=scenes,

            durations=actual_durations,

            output_path=subtitle_path,
        )

        progress.progress(
            70
        )

        # ====================================================
        # STEP 5
        # VIDEO RENDERING
        # ====================================================

        status.info(
            "🎬 Step 5/6 — Rendering scenes, camera movement, "
            "audio and subtitles..."
        )

        final_video = build_video(
            image_files=image_files,

            audio_files=audio_files,

            # IMPORTANT:
            # Use actual TTS durations.
            durations=actual_durations,

            animations=animations,

            subtitle_path=subtitle_path,

            work_dir=job_dir,
        )

        progress.progress(
            95
        )

        # ====================================================
        # STEP 6
        # FINALIZE
        # ====================================================

        status.info(
            "✨ Step 6/6 — Finalizing your educational video..."
        )

        if not final_video.exists():

            raise RuntimeError(
                "FFmpeg completed but the final MP4 "
                "file was not created."
            )

        video_bytes = (
            final_video.read_bytes()
        )

        if len(video_bytes) == 0:

            raise RuntimeError(
                "The final MP4 file is empty."
            )

        progress.progress(
            100
        )

        status.success(
            "🎉 Educational video generated successfully!"
        )

        scene_status.empty()

        # ====================================================
        # TOTAL ACTUAL DURATION
        # ====================================================

        total_actual_duration = sum(
            actual_durations
        )

        # ====================================================
        # VIDEO INFORMATION
        # ====================================================

        st.divider()

        st.subheader(
            f"🎬 {plan.get('title', 'Educational Video')}"
        )

        col1, col2, col3 = st.columns(
            3
        )

        with col1:

            st.metric(
                "Scenes",
                len(scenes),
            )

        with col2:

            st.metric(
                "Actual Duration",
                f"{total_actual_duration:.1f}s",
            )

        with col3:

            st.metric(
                "Language",
                language,
            )

        # ====================================================
        # VIDEO PREVIEW
        # ====================================================

        st.markdown(
            '<div class="section-title">🎥 Video Preview</div>',
            unsafe_allow_html=True,
        )

        st.video(
            video_bytes
        )

        # ====================================================
        # DOWNLOAD
        # ====================================================

        st.download_button(
            label="⬇️ Download Educational MP4",

            data=video_bytes,

            file_name=(
                "AIVA_AI_Educational_Video.mp4"
            ),

            mime="video/mp4",

            use_container_width=True,
        )

        # ====================================================
        # SUBTITLE PREVIEW
        # ====================================================

        with st.expander(
            "📝 View Synchronized Subtitles",
            expanded=False,
        ):

            st.code(
                subtitle_path.read_text(
                    encoding="utf-8"
                ),
                language="text",
            )

        # ====================================================
        # NARRATION SUMMARY
        # ====================================================

        with st.expander(
            "🗣️ View Complete AI Narration",
            expanded=False,
        ):

            for index, scene in enumerate(
                scenes,
                start=1,
            ):

                st.markdown(
                    f"### Scene {index}"
                )

                st.write(
                    scene.get(
                        "narration",
                        "",
                    )
                )

                st.caption(
                    f"Audio duration: "
                    f"{actual_durations[index - 1]:.2f} seconds"
                )

        # ====================================================
        # SUCCESS MESSAGE
        # ====================================================

        st.success(
            f"""
🎉 Your educational video is ready!

Title:
{plan.get('title', 'Educational Video')}

Scenes:
{len(scenes)}

Actual duration:
{total_actual_duration:.1f} seconds

Language:
{language}

Education level:
{education_level}

The narration duration was measured from the
actual generated audio, so complete voice lines
are preserved.
"""
        )

    # ========================================================
    # ERROR HANDLING
    # ========================================================

    except Exception as exc:

        progress.empty()

        scene_status.empty()

        status.error(
            "❌ Video generation stopped."
        )

        st.error(
            "Something went wrong while generating "
            "the educational video."
        )

        # -----------------------------------------------
        # IMPORTANT ERROR MESSAGE
        # -----------------------------------------------

        st.exception(
            exc
        )

        st.warning(
            """
The application does not automatically switch
to a paid AI provider.

Common causes include:

• Groq API key or model problem
• Hugging Face image inference permission
• Free inference limit
• TTS service problem
• FFmpeg rendering problem
• Invalid AI-generated scene data

Your API keys are never displayed by this application.
"""
        )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "🎓 AI Educational Video Generator • "
    "Groq + Qwen • Hugging Face + FLUX • "
    "Edge TTS • FFmpeg"
)
